# ----
# Site

title: Tres Hermanas
url: "https://treshermanaspr.github.io"
baseurl:
google_analytics_key:
eventbrite_embed:
timezone: AST

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Puerto Rico projects by three young sisters.
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Tres Hermanas
  links:

# -----
# Build

timezone: AST

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: page

# -----------
# CloudCannon

_comments:
  background_image: Image shown behind the content.
  map: Update the map location and display settings.
  latitude: Coordinates for the center marker on the map.
  longitude: Coordinates for the center marker on the map.
  zoom: The zoom level for the map.
  timezone: The timezone the event dates are listed in
